version: "3.8"
services:
  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:v0.47.2 
    container_name: cadvisor 
    restart: always 
    ports:
      - 8080:8080
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data/ha/:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      DISABLE_JEMALLOC: true

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "7080:80/tcp"
    environment:
      TZ: 'Europe/Istanbul'
      WEBPASSWORD: 'd~ANM@^/YU?OvuxVIRy,{[p5'
      CORS_HOSTS: "orangepi-hole.onurcecen.com"
    volumes:
      - '/data/pihole/etc-pihole:/etc/pihole'
      - '/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      - CAP_NET_RAW
    restart: unless-stopped
